server.port: 8082
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/grocery-shop
    username: grocery-shop-admin
    password: grocery-shop-admin
#  security:
#    user:
#      name: user
#      password: 1234
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
